language: python
python:
  - "3.6"

services:
  postgresql

addons:
  chrome: stable

after_script:
  - chmod +x ~/build.sh
  - chmod 777 ./tests/LPT/LuluPerfTest.jar
  - bash ~/build.sh
  - java -version
  - sudo ./tests/LPT/LuluPerfTest.jar ./tests/LPT/basic_test.json

script: python -m unittest discover tests

install:
  - pip install flask
  - pip install psycopg2
  - wget -N https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo apt-get install binfmt-support